### ISSUE TITLE
`Either` and `Result` missing in protobufs encoding

### ISSUE THREAD

**Issue by aherrmann** [mirage/mirage-lambda#17]
The `Value` type in the protobufs encoding is missing cases for `Either` and `Result` values.

**Comment by dinosaure** [comment]
`Value` is a mapping between OCaml/Haskell value and derive from primitives (first class) values available on OCaml/Haskell. The way used to make an `Either`/`Result` value is to use constructor `L`/`R`/`Ok` or `Error` as an expression.

Like: `Unop (Ok, (Int, (Value (Int 42))` (of course, because the language is monomorphic, you need to specify the type again). Then, because we need to specify the type, we can not put in the `Value` type a case to wrap a `Result`/`Either` value because we can not determine the type from nothing.

**Comment by dinosaure** [comment]
See #19
